name: GameControl
main: ru.boomearo.gamecontrol.GameControl
version: 0.1
author: BoomEaro
description: GameControl
api-version: 1.13
depend: [EssentialsSpawn, FastAsyncWorldEdit, ServerUtils, Board]
commands:
  gamecontrol:
    usage: /gamecontrol
    description: gamecontrol